name: Release
 
on:
  release:
    types: [published]
 
jobs:
  stage:
    uses: bitovi/.github/.github/workflows/npm-stage-publish.yml@main
    permissions:
      contents: read
      id-token: write